services:
  stores:
    build: .
    container_name: stores
    restart: unless-stopped
    environment:
      - SERVICE_NAME=stores
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DEBUG=${DEBUG}
      - AUTOMIGRATE=${AUTOMIGRATE}
