// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/makesalekz/stores/ent/schema"
	"github.com/makesalekz/stores/ent/store"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	storeMixin := schema.Store{}.Mixin()
	storeMixinHooks0 := storeMixin[0].Hooks()
	store.Hooks[0] = storeMixinHooks0[0]
	storeMixinInters0 := storeMixin[0].Interceptors()
	store.Interceptors[0] = storeMixinInters0[0]
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescName is the schema descriptor for name field.
	storeDescName := storeFields[2].Descriptor()
	// store.NameValidator is a validator for the "name" field. It is called by the builders before save.
	store.NameValidator = storeDescName.Validators[0].(func(string) error)
	// storeDescAddress is the schema descriptor for address field.
	storeDescAddress := storeFields[3].Descriptor()
	// store.DefaultAddress holds the default value on creation for the address field.
	store.DefaultAddress = storeDescAddress.Default.(string)
	// storeDescPhone is the schema descriptor for phone field.
	storeDescPhone := storeFields[6].Descriptor()
	// store.DefaultPhone holds the default value on creation for the phone field.
	store.DefaultPhone = storeDescPhone.Default.(string)
	// storeDescWorkHours is the schema descriptor for work_hours field.
	storeDescWorkHours := storeFields[7].Descriptor()
	// store.DefaultWorkHours holds the default value on creation for the work_hours field.
	store.DefaultWorkHours = storeDescWorkHours.Default.(string)
	// storeDescIsActive is the schema descriptor for is_active field.
	storeDescIsActive := storeFields[8].Descriptor()
	// store.DefaultIsActive holds the default value on creation for the is_active field.
	store.DefaultIsActive = storeDescIsActive.Default.(bool)
	// storeDescCreatedAt is the schema descriptor for created_at field.
	storeDescCreatedAt := storeFields[10].Descriptor()
	// store.DefaultCreatedAt holds the default value on creation for the created_at field.
	store.DefaultCreatedAt = storeDescCreatedAt.Default.(func() time.Time)
	// storeDescUpdatedAt is the schema descriptor for updated_at field.
	storeDescUpdatedAt := storeFields[11].Descriptor()
	// store.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	store.DefaultUpdatedAt = storeDescUpdatedAt.Default.(func() time.Time)
	// store.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	store.UpdateDefaultUpdatedAt = storeDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.14.2"                                         // Version of ent codegen.
	Sum     = "h1:ywld/j2Rx4EmnIKs8eZ29cbFA1zpB+DA9TLL5l3rlq0=" // Sum of ent codegen.
)
