// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/stores/internal/biz"
	"gitlab.calendaria.team/services/stores/internal/conf"
	"gitlab.calendaria.team/services/stores/internal/data"
	"gitlab.calendaria.team/services/stores/internal/server"
	"gitlab.calendaria.team/services/stores/internal/service"
	"gitlab.calendaria.team/services/utils/v4/config"
	"gitlab.calendaria.team/services/utils/v4/jwt"
	"gitlab.calendaria.team/services/utils/v4/tracing"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	iConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(iConfig)
	if err != nil {
		return nil, nil, err
	}
	iTracer := tracing.NewTracer(iConfig)
	dataData, cleanup, err := data.NewData(bootstrap, iConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	storesRepo := data.NewStoresRepo(dataData)
	storesUsecase, err := biz.NewStoresUsecase(logger, storesRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	storesService := service.NewStoresService(storesUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, iTracer, storesService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
