// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString},
		{Name: "address", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "lat", Type: field.TypeFloat64, Nullable: true},
		{Name: "lon", Type: field.TypeFloat64, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "work_hours", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "responsible_id", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "store_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{StoresColumns[2]},
			},
			{
				Name:    "store_tenant_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{StoresColumns[2], StoresColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StoresTable,
	}
)

func init() {
}
