// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/stores/v1/models.proto

package stores_v1

import (
	_ "gitlab.calendaria.team/services/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Lat           *float64               `protobuf:"fixed64,5,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,6,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	WorkHours     string                 `protobuf:"bytes,8,opt,name=work_hours,json=workHours,proto3" json:"work_hours,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ResponsibleId *int64                 `protobuf:"varint,10,opt,name=responsible_id,json=responsibleId,proto3,oneof" json:"responsible_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_api_stores_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Store) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Store) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Store) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *Store) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Store) GetWorkHours() string {
	if x != nil {
		return x.WorkHours
	}
	return ""
}

func (x *Store) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Store) GetResponsibleId() int64 {
	if x != nil && x.ResponsibleId != nil {
		return *x.ResponsibleId
	}
	return 0
}

func (x *Store) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Store) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_stores_v1_models_proto protoreflect.FileDescriptor

const file_api_stores_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/stores/v1/models.proto\x12\tstores.v1\x1a\x19api/utils/v1/models.proto\"\xef\x02\n" +
	"\x05Store\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x15\n" +
	"\x03lat\x18\x05 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x06 \x01(\x01H\x01R\x03lon\x88\x01\x01\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"work_hours\x18\b \x01(\tR\tworkHours\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12*\n" +
	"\x0eresponsible_id\x18\n" +
	" \x01(\x03H\x02R\rresponsibleId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAtB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lonB\x11\n" +
	"\x0f_responsible_idBM\n" +
	"\tstores.v1P\x01Z>gitlab.calendaria.team/services/stores/api/stores/v1;stores_v1b\x06proto3"

var (
	file_api_stores_v1_models_proto_rawDescOnce sync.Once
	file_api_stores_v1_models_proto_rawDescData []byte
)

func file_api_stores_v1_models_proto_rawDescGZIP() []byte {
	file_api_stores_v1_models_proto_rawDescOnce.Do(func() {
		file_api_stores_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stores_v1_models_proto_rawDesc), len(file_api_stores_v1_models_proto_rawDesc)))
	})
	return file_api_stores_v1_models_proto_rawDescData
}

var file_api_stores_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_stores_v1_models_proto_goTypes = []any{
	(*Store)(nil), // 0: stores.v1.Store
}
var file_api_stores_v1_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_stores_v1_models_proto_init() }
func file_api_stores_v1_models_proto_init() {
	if File_api_stores_v1_models_proto != nil {
		return
	}
	file_api_stores_v1_models_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stores_v1_models_proto_rawDesc), len(file_api_stores_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_stores_v1_models_proto_goTypes,
		DependencyIndexes: file_api_stores_v1_models_proto_depIdxs,
		MessageInfos:      file_api_stores_v1_models_proto_msgTypes,
	}.Build()
	File_api_stores_v1_models_proto = out.File
	file_api_stores_v1_models_proto_goTypes = nil
	file_api_stores_v1_models_proto_depIdxs = nil
}
