// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/stores/v1/stores.proto

package stores_v1

import (
	v1 "github.com/makesalekz/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Lat           *float64               `protobuf:"fixed64,3,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,4,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	WorkHours     string                 `protobuf:"bytes,6,opt,name=work_hours,json=workHours,proto3" json:"work_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreRequest) Reset() {
	*x = CreateStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreRequest) ProtoMessage() {}

func (x *CreateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreRequest.ProtoReflect.Descriptor instead.
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStoreRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateStoreRequest) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *CreateStoreRequest) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *CreateStoreRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateStoreRequest) GetWorkHours() string {
	if x != nil {
		return x.WorkHours
	}
	return ""
}

type UpdateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int64                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Lat           *float64               `protobuf:"fixed64,4,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,5,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	WorkHours     string                 `protobuf:"bytes,7,opt,name=work_hours,json=workHours,proto3" json:"work_hours,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStoreRequest) Reset() {
	*x = UpdateStoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreRequest) ProtoMessage() {}

func (x *UpdateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStoreRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *UpdateStoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStoreRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateStoreRequest) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *UpdateStoreRequest) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *UpdateStoreRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateStoreRequest) GetWorkHours() string {
	if x != nil {
		return x.WorkHours
	}
	return ""
}

func (x *UpdateStoreRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int64                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{2}
}

func (x *StoreRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type ListStoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlyActive    bool                   `protobuf:"varint,1,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{3}
}

func (x *ListStoresRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListStoresRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListStoresReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresReply) Reset() {
	*x = ListStoresReply{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresReply) ProtoMessage() {}

func (x *ListStoresReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresReply.ProtoReflect.Descriptor instead.
func (*ListStoresReply) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{4}
}

func (x *ListStoresReply) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *ListStoresReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type StoreReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreReply) Reset() {
	*x = StoreReply{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReply) ProtoMessage() {}

func (x *StoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReply.ProtoReflect.Descriptor instead.
func (*StoreReply) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{5}
}

func (x *StoreReply) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type SetStoreResponsibleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int64                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	MemberId      int64                  `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStoreResponsibleRequest) Reset() {
	*x = SetStoreResponsibleRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStoreResponsibleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStoreResponsibleRequest) ProtoMessage() {}

func (x *SetStoreResponsibleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStoreResponsibleRequest.ProtoReflect.Descriptor instead.
func (*SetStoreResponsibleRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{6}
}

func (x *SetStoreResponsibleRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *SetStoreResponsibleRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type GetStoresByCoordinatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreIds      []int64                `protobuf:"varint,1,rep,packed,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoresByCoordinatesRequest) Reset() {
	*x = GetStoresByCoordinatesRequest{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoresByCoordinatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoresByCoordinatesRequest) ProtoMessage() {}

func (x *GetStoresByCoordinatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoresByCoordinatesRequest.ProtoReflect.Descriptor instead.
func (*GetStoresByCoordinatesRequest) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{7}
}

func (x *GetStoresByCoordinatesRequest) GetStoreIds() []int64 {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

type StoreCoordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           *float64               `protobuf:"fixed64,3,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,4,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreCoordinate) Reset() {
	*x = StoreCoordinate{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCoordinate) ProtoMessage() {}

func (x *StoreCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCoordinate.ProtoReflect.Descriptor instead.
func (*StoreCoordinate) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{8}
}

func (x *StoreCoordinate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreCoordinate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreCoordinate) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *StoreCoordinate) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

type GetStoresByCoordinatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*StoreCoordinate     `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoresByCoordinatesReply) Reset() {
	*x = GetStoresByCoordinatesReply{}
	mi := &file_api_stores_v1_stores_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoresByCoordinatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoresByCoordinatesReply) ProtoMessage() {}

func (x *GetStoresByCoordinatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_stores_v1_stores_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoresByCoordinatesReply.ProtoReflect.Descriptor instead.
func (*GetStoresByCoordinatesReply) Descriptor() ([]byte, []int) {
	return file_api_stores_v1_stores_proto_rawDescGZIP(), []int{9}
}

func (x *GetStoresByCoordinatesReply) GetStores() []*StoreCoordinate {
	if x != nil {
		return x.Stores
	}
	return nil
}

var File_api_stores_v1_stores_proto protoreflect.FileDescriptor

const file_api_stores_v1_stores_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/stores/v1/stores.proto\x12\tstores.v1\x1a\x19api/utils/v1/models.proto\x1a\x1aapi/stores/v1/models.proto\"\xb5\x01\n" +
	"\x12CreateStoreRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x15\n" +
	"\x03lat\x18\x03 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x04 \x01(\x01H\x01R\x03lon\x88\x01\x01\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"work_hours\x18\x06 \x01(\tR\tworkHoursB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lon\"\xed\x01\n" +
	"\x12UpdateStoreRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x03R\astoreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x15\n" +
	"\x03lat\x18\x04 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x05 \x01(\x01H\x01R\x03lon\x88\x01\x01\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"work_hours\x18\a \x01(\tR\tworkHours\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActiveB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lon\")\n" +
	"\fStoreRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x03R\astoreId\"k\n" +
	"\x11ListStoresRequest\x12\x1f\n" +
	"\vonly_active\x18\x01 \x01(\bR\n" +
	"onlyActive\x125\n" +
	"\bpaginate\x18\x02 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"p\n" +
	"\x0fListStoresReply\x12(\n" +
	"\x06stores\x18\x01 \x03(\v2\x10.stores.v1.StoreR\x06stores\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"4\n" +
	"\n" +
	"StoreReply\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.stores.v1.StoreR\x05store\"T\n" +
	"\x1aSetStoreResponsibleRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x03R\astoreId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x03R\bmemberId\"<\n" +
	"\x1dGetStoresByCoordinatesRequest\x12\x1b\n" +
	"\tstore_ids\x18\x01 \x03(\x03R\bstoreIds\"s\n" +
	"\x0fStoreCoordinate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x03lat\x18\x03 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x04 \x01(\x01H\x01R\x03lon\x88\x01\x01B\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lon\"Q\n" +
	"\x1bGetStoresByCoordinatesReply\x122\n" +
	"\x06stores\x18\x01 \x03(\v2\x1a.stores.v1.StoreCoordinateR\x06stores2\x95\x04\n" +
	"\x06Stores\x12C\n" +
	"\vCreateStore\x12\x1d.stores.v1.CreateStoreRequest\x1a\x15.stores.v1.StoreReply\x12C\n" +
	"\vUpdateStore\x12\x1d.stores.v1.UpdateStoreRequest\x1a\x15.stores.v1.StoreReply\x12<\n" +
	"\vDeleteStore\x12\x17.stores.v1.StoreRequest\x1a\x14.utils.v1.EmptyReply\x12:\n" +
	"\bGetStore\x12\x17.stores.v1.StoreRequest\x1a\x15.stores.v1.StoreReply\x12F\n" +
	"\n" +
	"ListStores\x12\x1c.stores.v1.ListStoresRequest\x1a\x1a.stores.v1.ListStoresReply\x12S\n" +
	"\x13SetStoreResponsible\x12%.stores.v1.SetStoreResponsibleRequest\x1a\x15.stores.v1.StoreReply\x12j\n" +
	"\x16GetStoresByCoordinates\x12(.stores.v1.GetStoresByCoordinatesRequest\x1a&.stores.v1.GetStoresByCoordinatesReplyBC\n" +
	"\tstores.v1P\x01Z4github.com/makesalekz/stores/api/stores/v1;stores_v1b\x06proto3"

var (
	file_api_stores_v1_stores_proto_rawDescOnce sync.Once
	file_api_stores_v1_stores_proto_rawDescData []byte
)

func file_api_stores_v1_stores_proto_rawDescGZIP() []byte {
	file_api_stores_v1_stores_proto_rawDescOnce.Do(func() {
		file_api_stores_v1_stores_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stores_v1_stores_proto_rawDesc), len(file_api_stores_v1_stores_proto_rawDesc)))
	})
	return file_api_stores_v1_stores_proto_rawDescData
}

var file_api_stores_v1_stores_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_stores_v1_stores_proto_goTypes = []any{
	(*CreateStoreRequest)(nil),            // 0: stores.v1.CreateStoreRequest
	(*UpdateStoreRequest)(nil),            // 1: stores.v1.UpdateStoreRequest
	(*StoreRequest)(nil),                  // 2: stores.v1.StoreRequest
	(*ListStoresRequest)(nil),             // 3: stores.v1.ListStoresRequest
	(*ListStoresReply)(nil),               // 4: stores.v1.ListStoresReply
	(*StoreReply)(nil),                    // 5: stores.v1.StoreReply
	(*SetStoreResponsibleRequest)(nil),    // 6: stores.v1.SetStoreResponsibleRequest
	(*GetStoresByCoordinatesRequest)(nil), // 7: stores.v1.GetStoresByCoordinatesRequest
	(*StoreCoordinate)(nil),               // 8: stores.v1.StoreCoordinate
	(*GetStoresByCoordinatesReply)(nil),   // 9: stores.v1.GetStoresByCoordinatesReply
	(*v1.PaginateRequest)(nil),            // 10: utils.v1.PaginateRequest
	(*Store)(nil),                         // 11: stores.v1.Store
	(*v1.PaginateReply)(nil),              // 12: utils.v1.PaginateReply
	(*v1.EmptyReply)(nil),                 // 13: utils.v1.EmptyReply
}
var file_api_stores_v1_stores_proto_depIdxs = []int32{
	10, // 0: stores.v1.ListStoresRequest.paginate:type_name -> utils.v1.PaginateRequest
	11, // 1: stores.v1.ListStoresReply.stores:type_name -> stores.v1.Store
	12, // 2: stores.v1.ListStoresReply.paginate:type_name -> utils.v1.PaginateReply
	11, // 3: stores.v1.StoreReply.store:type_name -> stores.v1.Store
	8,  // 4: stores.v1.GetStoresByCoordinatesReply.stores:type_name -> stores.v1.StoreCoordinate
	0,  // 5: stores.v1.Stores.CreateStore:input_type -> stores.v1.CreateStoreRequest
	1,  // 6: stores.v1.Stores.UpdateStore:input_type -> stores.v1.UpdateStoreRequest
	2,  // 7: stores.v1.Stores.DeleteStore:input_type -> stores.v1.StoreRequest
	2,  // 8: stores.v1.Stores.GetStore:input_type -> stores.v1.StoreRequest
	3,  // 9: stores.v1.Stores.ListStores:input_type -> stores.v1.ListStoresRequest
	6,  // 10: stores.v1.Stores.SetStoreResponsible:input_type -> stores.v1.SetStoreResponsibleRequest
	7,  // 11: stores.v1.Stores.GetStoresByCoordinates:input_type -> stores.v1.GetStoresByCoordinatesRequest
	5,  // 12: stores.v1.Stores.CreateStore:output_type -> stores.v1.StoreReply
	5,  // 13: stores.v1.Stores.UpdateStore:output_type -> stores.v1.StoreReply
	13, // 14: stores.v1.Stores.DeleteStore:output_type -> utils.v1.EmptyReply
	5,  // 15: stores.v1.Stores.GetStore:output_type -> stores.v1.StoreReply
	4,  // 16: stores.v1.Stores.ListStores:output_type -> stores.v1.ListStoresReply
	5,  // 17: stores.v1.Stores.SetStoreResponsible:output_type -> stores.v1.StoreReply
	9,  // 18: stores.v1.Stores.GetStoresByCoordinates:output_type -> stores.v1.GetStoresByCoordinatesReply
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_stores_v1_stores_proto_init() }
func file_api_stores_v1_stores_proto_init() {
	if File_api_stores_v1_stores_proto != nil {
		return
	}
	file_api_stores_v1_models_proto_init()
	file_api_stores_v1_stores_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_stores_v1_stores_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_stores_v1_stores_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stores_v1_stores_proto_rawDesc), len(file_api_stores_v1_stores_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stores_v1_stores_proto_goTypes,
		DependencyIndexes: file_api_stores_v1_stores_proto_depIdxs,
		MessageInfos:      file_api_stores_v1_stores_proto_msgTypes,
	}.Build()
	File_api_stores_v1_stores_proto = out.File
	file_api_stores_v1_stores_proto_goTypes = nil
	file_api_stores_v1_stores_proto_depIdxs = nil
}
