// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/makesalekz/stores/ent/store"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   store.Table,
			Columns: store.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: store.FieldID,
			},
		},
		Type: "Store",
		Fields: map[string]*sqlgraph.FieldSpec{
			store.FieldDeletedAt:     {Type: field.TypeTime, Column: store.FieldDeletedAt},
			store.FieldTenantID:      {Type: field.TypeInt64, Column: store.FieldTenantID},
			store.FieldName:          {Type: field.TypeString, Column: store.FieldName},
			store.FieldAddress:       {Type: field.TypeString, Column: store.FieldAddress},
			store.FieldLat:           {Type: field.TypeFloat64, Column: store.FieldLat},
			store.FieldLon:           {Type: field.TypeFloat64, Column: store.FieldLon},
			store.FieldPhone:         {Type: field.TypeString, Column: store.FieldPhone},
			store.FieldWorkHours:     {Type: field.TypeString, Column: store.FieldWorkHours},
			store.FieldIsActive:      {Type: field.TypeBool, Column: store.FieldIsActive},
			store.FieldResponsibleID: {Type: field.TypeInt64, Column: store.FieldResponsibleID},
			store.FieldCreatedAt:     {Type: field.TypeTime, Column: store.FieldCreatedAt},
			store.FieldUpdatedAt:     {Type: field.TypeTime, Column: store.FieldUpdatedAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (sq *StoreQuery) addPredicate(pred func(s *sql.Selector)) {
	sq.predicates = append(sq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the StoreQuery builder.
func (sq *StoreQuery) Filter() *StoreFilter {
	return &StoreFilter{config: sq.config, predicateAdder: sq}
}

// addPredicate implements the predicateAdder interface.
func (m *StoreMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the StoreMutation builder.
func (m *StoreMutation) Filter() *StoreFilter {
	return &StoreFilter{config: m.config, predicateAdder: m}
}

// StoreFilter provides a generic filtering capability at runtime for StoreQuery.
type StoreFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *StoreFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *StoreFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(store.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *StoreFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(store.FieldDeletedAt))
}

// WhereTenantID applies the entql int64 predicate on the tenant_id field.
func (f *StoreFilter) WhereTenantID(p entql.Int64P) {
	f.Where(p.Field(store.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *StoreFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(store.FieldName))
}

// WhereAddress applies the entql string predicate on the address field.
func (f *StoreFilter) WhereAddress(p entql.StringP) {
	f.Where(p.Field(store.FieldAddress))
}

// WhereLat applies the entql float64 predicate on the lat field.
func (f *StoreFilter) WhereLat(p entql.Float64P) {
	f.Where(p.Field(store.FieldLat))
}

// WhereLon applies the entql float64 predicate on the lon field.
func (f *StoreFilter) WhereLon(p entql.Float64P) {
	f.Where(p.Field(store.FieldLon))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *StoreFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(store.FieldPhone))
}

// WhereWorkHours applies the entql string predicate on the work_hours field.
func (f *StoreFilter) WhereWorkHours(p entql.StringP) {
	f.Where(p.Field(store.FieldWorkHours))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *StoreFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(store.FieldIsActive))
}

// WhereResponsibleID applies the entql int64 predicate on the responsible_id field.
func (f *StoreFilter) WhereResponsibleID(p entql.Int64P) {
	f.Where(p.Field(store.FieldResponsibleID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *StoreFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(store.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *StoreFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(store.FieldUpdatedAt))
}
